import { Metadata } from "next"
import FooClient from "./foo_client"

export const metadata: Metadata = {
    title: "Foo page",
    description: "Generated by create next app",
}

export default function FooPage() {
    return (
        <FooClient />
    )
}